---
- hosts: servera.lab.example.com
  connection: ssh
  user: test
  become: yes
  tasks:
  - name: adding users
    user: name={{ item }} state=present
    with_items:
    - user1
    - user2
    - user3
    - user4

