--- ### my first play book
- hosts: servera.lab.example.com
  connection: ssh
  user: test
  become: yes
  gather_facts: no
  vars:
    playbook_version: 1b
  vars_files:
  - conf/copyright.yml
  - conf/webdefaults.yml
  tasks:
  - name: install apache web server
    yum:  name=httpd state=installed
  - name: verify lynx
    yum:  name=lynx state=present  

