---
- hosts: web_hosts
  remote_user: test
  become: true
  gather_facts: no
  tasks:
  - name: install httpd package
    yum: name=httpd state=latest
  - pause: prompt="hit enter to continue"
  - name: install lynx package
    yum: name=lynx state=latest
