---
- hosts: servera.lab.example.com
  remote_user: test
  become: true
  tasks:
  - stat: path=/var/log/messages
    register: p
  - debug: var=p  
  - debug: msg="Path exists and is a directory"
    when: p.stat.isdir == 1
