- hosts: localhost
  remote_user: test
  become: true
  vars:
    userName: adil
    Pass: 123456
    ConnectionType: SFTP
  tasks:
  - template: src=test.conf.j2 dest=/home/test/test.conf  owner=test group=test mode=0750
